
spring:
  application:
    name: Prod

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
    fetch-registry: 'true'
    register-with-eureka: 'true'
  instance:
    prefer-ip-address: 'true'
